version: "3.9"

services:
  web:
    build: .
    container_name: super-market-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=supermarketdb
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: mysql:8.0
    container_name: super-market-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: supermarketdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"   # expose externally on 3307 to avoid conflicts
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
